version: '3.8'

services:
  app:
    # A imagem é compilada automaticamente na nuvem pelo GitHub Actions e baixada no Portainer
    image: ghcr.io/cristhian-sancore/sistema-fassil1:latest
    # build: . # Descomente apenas se for rodar build manual local no seu computador
    container_name: grupofas_app
    restart: always
    ports:
      - "8055:80"
    volumes:
      # Mantém as mídias e documentos históricos persisitidos no host para não perder anexos antigos
      - ./public_html/gerenciar/midias:/var/www/html/public_html/gerenciar/midias
      - ./public_html/documentos:/var/www/html/public_html/documentos
    environment:
      - DB_HOST=db
      - DB_USER=grupofas_admin
      - DB_PASS=fassil3017#
      - DB_NAME=grupofas_sistema
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: grupofas_db
    restart: always
    command: --sql-mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --max-allowed-packet=64M
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Senha de root interna do MySQL
      MYSQL_DATABASE: grupofas_sistema
      MYSQL_USER: grupofas_admin
      MYSQL_PASSWORD: fassil3017#
    ports:
      - "33060:3306" # Mapeando a porta do MySQL para 33060 externa para evitar conflitos na porta 3306
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d # Importação automática do dump grupofas_sistema.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
